In [1]:
from subprocess import check_output
print(check_output(["ls", "data"]).decode("utf8"))

dataset_three.csv
numeric_one.csv
numeric_two_extrafeatures.csv
test.csv
train.csv
train_new_innerjoin.csv
train_new_leftjoin.csv
train_new_numeric.csv

In [2]:
import pandas as pd

# Merge:
train.csv, test.csv with new_data.csv - join tables on project_id (remove the kkst prefix) and id.

In [3]:
new_dataset = pd.read_csv('data/dataset_three.csv')

/home/nahmed/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (29,30,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
new_dataset.shape

(169832, 33)

In [5]:
new_dataset.head(2
                )

,id,photo,name,blurb,goal,pledged,state,slug,disable_communication,country,...,location,category,profile,spotlight,urls,source_url,friends,is_starred,is_backing,permissions
0,1762037418,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",The danger of plastics in our oceans,Artwork creating a powerful statement about th...,10000.0,2.0,failed,the-danger-of-plastics-in-our-oceans,False,US,...,"{""country"":""US"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",False,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
1,1225393342,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",Enpowering Women thru ART,I make new age modern contemporary art of famo...,5000.0,0.0,failed,enpowering-women-thru-art,False,CA,...,"{""country"":""CA"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",False,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN

 # previous attempt to match data on project_id

In [6]:
old_train = pd.read_csv('data/train_new.csv')

In [7]:
old_train.shape

(108129, 18)

In [25]:
old_test = pd.read_csv('data/test.csv')

In [26]:
old_test.head(2)

,project_id,name,desc,goal,keywords,disable_communication,country,currency,deadline,state_changed_at,created_at,launched_at
0,kkst917493670,Bràthair.,"My first film, of many to come. Trying to purs...",7000.0,brathair,False,US,USD,1449619185,1449619185,1446002581,1446159585
1,kkst1664901914,THE SCREENWRITER,A young man that has earned his master's in sc...,35000.0,the-screenwriter,False,US,USD,1453435620,1453435620,1450297323,1450411620

# Strip 'kkst' from project_id

In [27]:
old_train['project_id'] = old_train['project_id'].map(lambda x: x.lstrip('kkst'))

In [28]:
old_train.head(1)

,project_id,name,desc,goal,keywords,disable_communication,country,currency,deadline,state_changed_at,created_at,launched_at,backers_count,final_status
0,1451568084,drawing for dollars,I like drawing pictures. and then i color them...,20.0,drawing-for-dollars,False,US,USD,1241333999,1241334017,1240600507,1240602723,3,1

In [29]:
old_test['project_id'] = old_test['project_id'].map(lambda x: x.lstrip('kkst'))

# Merge/Join with the new data

In [30]:
# using simple inner join - Pandas merge() defaults to an “inner” merge operation
# only the joined rows - probably be smaller than the real dataset - old_train
merged_train = pd.merge(old_train,
                 new_dataset[['id', 'photo', 'pledged', 'state', 'staff_pick', 'is_starrable', 'static_usd_rate', 'usd_pledged', 'creator', 'category', 'profile', 'spotlight', ]],
                 left_on='project_id',
                 right_on='id')
merged_train.head()

Empty DataFrame
Columns: [project_id, name, desc, goal, keywords, disable_communication, country, currency, deadline, state_changed_at, created_at, launched_at, backers_count, final_status, id, photo, pledged, state, staff_pick, is_starrable, static_usd_rate, usd_pledged, creator, category, profile, spotlight]
Index: []

[0 rows x 26 columns]

In [31]:
# using simple left join - shape will be same as left table i.e. 'old_train' - with joined and not joined rows.
merged_train_two = pd.merge(old_train,
                            new_dataset[['id', 'photo', 'pledged', 'state', 'staff_pick', 'is_starrable', 'static_usd_rate', 'usd_pledged', 'creator', 'category', 'profile', 'spotlight', ]],
                            left_on='project_id',
                            right_on='id', 
                            how='left')
merged_train_two.head()

,project_id,name,desc,goal,keywords,disable_communication,country,currency,deadline,state_changed_at,...,pledged,state,staff_pick,is_starrable,static_usd_rate,usd_pledged,creator,category,profile,spotlight
0,1451568084,drawing for dollars,I like drawing pictures. and then i color them...,20.0,drawing-for-dollars,False,US,USD,1241333999,1241334017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1474482071,Sponsor Dereck Blackburn (Lostwars) Artist in ...,"I, Dereck Blackburn will be taking upon an inc...",300.0,sponsor-dereck-blackburn-lostwars-artist-in-re...,False,US,USD,1242429000,1242432018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,183622197,Mr. Squiggles,So I saw darkpony's successfully funded drawin...,30.0,mr-squiggles,False,US,USD,1243027560,1243027818,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,597742710,Help me write my second novel.,Do your part to help out starving artists and ...,500.0,help-me-write-my-second-novel,False,US,USD,1243555740,1243556121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1913131122,Support casting my sculpture in bronze,"I'm nearing completion on a sculpture, current...",2000.0,support-casting-my-sculpture-in-bronze,False,US,USD,1243769880,1243770317,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
merged_train.shape

(0, 26)

In [35]:
merged_train_two.shape

(108129, 26)

In [32]:
merged_test = pd.merge(old_test,
                            new_dataset[['id', 'photo', 'pledged', 'state', 'staff_pick', 'is_starrable', 'static_usd_rate', 'usd_pledged', 'creator', 'category', 'profile', 'spotlight', ]],
                            left_on='project_id',
                            right_on='id', 
                            how='left')
merged_test.head()

,project_id,name,desc,goal,keywords,disable_communication,country,currency,deadline,state_changed_at,...,pledged,state,staff_pick,is_starrable,static_usd_rate,usd_pledged,creator,category,profile,spotlight
0,917493670,Bràthair.,"My first film, of many to come. Trying to purs...",7000.0,brathair,False,US,USD,1449619185,1449619185,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1664901914,THE SCREENWRITER,A young man that has earned his master's in sc...,35000.0,the-screenwriter,False,US,USD,1453435620,1453435620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,925125077,The Hornets Nest the Fairmont Heights Story,Film about a high school constructed for negro...,49500.0,the-hornets-nest-the-fairmont-heights-story,False,US,USD,1451780700,1451780700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1427645275,BROTHERS Season 2 - Groundbreaking Transgender...,The acclaimed series about a group of transgen...,40000.0,brothers-season-2-groundbreaking-transgender-male,False,US,USD,1445021518,1445021530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1714249266,Blackdom the movie,Blackdom's history offers a new narrative tha...,20000.0,blackdom-the-movie,False,US,USD,1462068840,1462068844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# No match found - on project_id and id (right - new dataset)

In [40]:
old_train.name.shape

(108129,)

In [41]:
new_dataset.name.shape

(169832,)

In [44]:
# not including the 'name' for columns of right table gave - keyerror.
merged_train = pd.merge(old_train,
                 new_dataset[['id', 'name', 'photo', 'pledged']],
                 on='name')
merged_train.head()

,project_id,name,desc,goal,keywords,disable_communication,country,currency,deadline,state_changed_at,created_at,launched_at,backers_count,final_status,id,photo,pledged
0,1451568084,drawing for dollars,I like drawing pictures. and then i color them...,20.0,drawing-for-dollars,False,US,USD,1241333999,1241334017,1240600507,1240602723,3,1,1703704063,"{""small"":""https://ksr-ugc.imgix.net/assets/011...",35.0
1,183622197,Mr. Squiggles,So I saw darkpony's successfully funded drawin...,30.0,mr-squiggles,False,US,USD,1243027560,1243027818,1242163613,1242164398,0,0,199916122,"{""small"":""https://ksr-ugc.imgix.net/assets/011...",0.0
2,597742710,Help me write my second novel.,Do your part to help out starving artists and ...,500.0,help-me-write-my-second-novel,False,US,USD,1243555740,1243556121,1240963795,1240966730,18,1,266044220,"{""small"":""https://ksr-ugc.imgix.net/assets/011...",563.0
3,1913131122,Support casting my sculpture in bronze,"I'm nearing completion on a sculpture, current...",2000.0,support-casting-my-sculpture-in-bronze,False,US,USD,1243769880,1243770317,1241177914,1241180541,1,0,1578671837,"{""small"":""https://ksr-ugc.imgix.net/assets/011...",25.0
4,1085176748,daily digest,I'm a fledgling videoblogger living in Brookly...,700.0,daily-digest,False,US,USD,1243815600,1243816219,1241050799,1241464468,14,0,1100844465,"{""small"":""https://ksr-ugc.imgix.net/assets/011...",700.0

In [45]:
merged_train.shape

(83096, 17)

# Inner join on 'name' returned 83086 rows.

In [12]:
# not including the 'name' for columns of right table gave - keyerror.
merged_train = pd.merge(old_train,
                        new_dataset[['name', 'photo', 'pledged', 'state', 'staff_pick', 
                             'is_starrable', 'static_usd_rate', 'usd_pledged', 'creator', 
                             'category', 'profile', 'spotlight', 'is_backing', 'is_starred']],
                         on='name')
merged_train.head()

,project_id,name,desc,description_size,goal,keywords,disable_communication,country,currency,deadline,...,staff_pick,is_starrable,static_usd_rate,usd_pledged,creator,category,profile,spotlight,is_backing,is_starred
0,kkst1451568084,drawing for dollars,I like drawing pictures. and then i color them...,134.0,20.0,drawing-for-dollars,False,US,USD,2009-05-03 06:59:59,...,True,False,1.0,35.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,NaN,NaN
1,kkst183622197,Mr. Squiggles,So I saw darkpony's successfully funded drawin...,385.0,30.0,mr-squiggles,False,US,USD,2009-05-22 21:26:00,...,False,False,1.0,0.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",False,NaN,NaN
2,kkst597742710,Help me write my second novel.,Do your part to help out starving artists and ...,129.0,500.0,help-me-write-my-second-novel,False,US,USD,2009-05-29 00:09:00,...,True,False,1.0,563.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,NaN,NaN
3,kkst1913131122,Support casting my sculpture in bronze,"I'm nearing completion on a sculpture, current...",384.0,2000.0,support-casting-my-sculpture-in-bronze,False,US,USD,2009-05-31 11:38:00,...,False,False,1.0,25.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",False,NaN,NaN
4,kkst1085176748,daily digest,I'm a fledgling videoblogger living in Brookly...,131.0,700.0,daily-digest,False,US,USD,2009-06-01 00:20:00,...,False,False,1.0,700.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,NaN,NaN

In [13]:
merged_train.shape

(83096, 31)

In [11]:
# not including the 'name' for columns of right table gave - keyerror.
merged_left_train = pd.merge(old_train,
                new_dataset[['name', 'photo', 'pledged', 'state', 'staff_pick', 
                             'is_starrable', 'static_usd_rate', 'usd_pledged', 'creator', 
                             'category', 'profile', 'spotlight', 'is_backing', 'is_starred']],
                 on='name', 
                 how='left')
merged_left_train.head()

,project_id,name,desc,description_size,goal,keywords,disable_communication,country,currency,deadline,...,staff_pick,is_starrable,static_usd_rate,usd_pledged,creator,category,profile,spotlight,is_backing,is_starred
0,kkst1451568084,drawing for dollars,I like drawing pictures. and then i color them...,134.0,20.0,drawing-for-dollars,False,US,USD,2009-05-03 06:59:59,...,True,False,1.0,35.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,NaN,NaN
1,kkst1474482071,Sponsor Dereck Blackburn (Lostwars) Artist in ...,"I, Dereck Blackburn will be taking upon an inc...",137.0,300.0,sponsor-dereck-blackburn-lostwars-artist-in-re...,False,US,USD,2009-05-15 23:10:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,kkst183622197,Mr. Squiggles,So I saw darkpony's successfully funded drawin...,385.0,30.0,mr-squiggles,False,US,USD,2009-05-22 21:26:00,...,False,False,1.0,0.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",False,NaN,NaN
3,kkst597742710,Help me write my second novel.,Do your part to help out starving artists and ...,129.0,500.0,help-me-write-my-second-novel,False,US,USD,2009-05-29 00:09:00,...,True,False,1.0,563.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,NaN,NaN
4,kkst1913131122,Support casting my sculpture in bronze,"I'm nearing completion on a sculpture, current...",384.0,2000.0,support-casting-my-sculpture-in-bronze,False,US,USD,2009-05-31 11:38:00,...,False,False,1.0,25.0,"{""urls"":{""web"":{""user"":""https://www.kickstarte...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",False,NaN,NaN

In [49]:
merged_left_train.shape

(108800, 25)

In [50]:
merged_left_train.to_csv('data/train_new_leftjoin.csv', index=False)  # index=False otherwise adds 'Unnamed' index

In [14]:
merged_train.to_csv('data/train_new_innerjoin.csv', index=False)  # index=False otherwise adds 'Unnamed' index